- name: Variables from files
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
    - name: Print override information
      ansible.builtin.debug:
        msg: "Hi, I am learning {{ Course }} in {{ Stream }}, Duration is {{ Duration }}."
