- name: Variables from files
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      prompt: Please enter username
      private: false
    - name: PASSWORD
      prompt: Please enter password
      private: true
  tasks:
    - name: Print information
      ansible.builtin.debug:
        msg: "Hi, Username: {{USERNAME}}. Password is: {{PASSWORD}}"
